#!/usr/bin/env bash
set -euo pipefail

dry_run=true
labels_arg=""
body_arg=""

while [ $# -gt 0 ]; do
    case "$1" in
    --labels)
        labels_arg="$2"
        shift
        ;;
    --force)
        dry_run=false
        ;;
    --body)
        body_arg="$2"
        shift
        ;;
    -h | --help)
        echo "Usage: gh comment [options]"
        echo "Options:"
        echo "  --labels <labels>  Specify labels to filter"
        echo "  --body <body>      Specify body of comment"
        echo "  --force            Do not dry run"
        echo "  -h, --help         Show this help message and exit"
        exit 0
        ;;
    esac
    shift
done

if [ -z "$body_arg" ]; then
    echo "Body is required"
    exit 1
fi

lines=$(
    gh pr list \
        --label "$labels_arg" \
        --json number,title,url \
        --jq '.[]'
)

if [ -z "$lines" ]; then
    echo "No pull requests found"
    exit 0
fi

while read -r line; do
    number=$(echo "$line" | jq -r '.number')
    title=$(echo "$line" | jq -r '.title')
    url=$(echo "$line" | jq -r '.url')

    echo "~~~"
    echo -e "\033[0;32m#$number\033[0m $title"
    echo -e "\033[0;33m$url\033[0m"

    if [ "$dry_run" = true ]; then
        echo "→ Dry run, skipping..."
        continue
    fi
    gh pr comment "$number" --body "$body_arg"
done <<<"$lines"
